version: "3.8"
services:
  db:
    image: mysql
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:1.8
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
      
  api:
    container_name: api
    image: doodleback
    restart: always
    ports: 
      - "8080:8080"

  front:
    image: doodlefront
    ports:
      - "90:90"
    volumes:
      - ./exampleconf/doodle.conf:/etc/nginx/conf.d/doodle.conf
      - ./exampleconf/pad.conf:/etc/nginx/conf.d/pad.conf
      - ./exampleconf/myadmin.conf:/etc/nginx/conf.d/myadmin.conf
    depends_on:
      - api
      - db
      - mail
      - etherpad

  myadmin:
    ports:
      - "8081:80"
    image: phpmyadmin
    container_name: myadmin
    environment:
      - PMA_HOST=db
